Update dfrab

diff --git a/bin/dfrab b/bin/dfrab
--- a/bin/dfrab
+++ b/bin/dfrab
@@ -65,6 +65,10 @@ if [[ "$1" == 'switch-profile' ]] ; then
     echo "Switched to $2"
     exit 0
   fi
+  if [[ ! -d ~/.dfrab/backups/$2 ]] ; then
+    echo "$2 does not exist so it cannot be switched to"
+    exit 2
+  fi
 fi
 
 if [[ "$1" == 'create-profile' ]] ; then
@@ -215,7 +219,7 @@ if [[ "$1" == 'rename-profile' ]] ; then
     echo "cannot change name to $3 because there is already a directory named that"
     exit 21
   fi
-  if [[ "$2" == $CURRENT_DFRAB_PROFILE ]] ; then
+  if [[ "$2" == $(basename $CURRENT_DFRAB_PROFILE) ]] ; then
     mv ~/.dfrab/backups/$2 ~/.dfrab/backups/$3
     if [[ ! -d ~/.dfrab/backups/$3 ]] ; then
       echo "fatal: failed to rename $2 to $3"
