Update dfrab

diff --git a/bin/dfrab b/bin/dfrab
--- a/bin/dfrab
+++ b/bin/dfrab
@@ -22,6 +22,10 @@ if [[ "$1" == 'init' ]] ; then
 fi
 
 if [[ "$1" == 'link' ]] ; then
+  if [[ "$2" == '.dfrab' ]] ; then
+    echo "Fatal: unable to link .dfrab"
+    exit 1
+  fi
   mv ~/$2 ~/.dfrab/current
   ln -s ~/.dfrab/current/$2 ~/$2
   exit 0
