Update dfrab

diff --git a/bin/dfrab b/bin/dfrab
--- a/bin/dfrab
+++ b/bin/dfrab
@@ -20,12 +20,20 @@ if [[ "$1" == 'init' ]] ; then
 fi
 
 if [[ "$1" == 'link' ]] ; then
+  if [[ "$2" == '.' ]] ; then
+    echo "Fatal: canot link ."
+    exit 1
+  fi
+  if [[ "$2" == '..' ]] ; then
+    echo "Fatal: cannot link .."
+    exit 1
+  fi
   if [[ "$2" == '.dfrab' ]] ; then
     echo "Fatal: unable to link .dfrab"
     exit 1
   fi
   if [[ -L "$2" ]]; then
-    echo "dfrab can't link symlinks"
+    echo "dfrab cannot link symlinks"
     exit 1
   fi
   if [[ ! -e "$2" ]] ; then
@@ -50,6 +58,13 @@ if [[ "$1" == 'create-profile' ]] ; then
     echo "$2 already exists, use a different name."
     exit 21
   fi
+  if [[ "$2" == '.' ]] ; then
+    echo "Fatal: cannot name profile ."
+    exit 1
+  fi
+  if [[ "$2" == '..' ]] ; then
+    echo "Fatal: canot name profile .."
+    exit 1
   if [[ ! -d ~/.dfrab/backups/$2 ]] ; then
     cp -r $CURRENT_DFRAB_PROFILE ~/.dfrab/backups/$2
     rm -f ~/.dfrab/current
@@ -62,6 +77,14 @@ if [[ "$1" == 'create-backup' ]] ; then
   if [[ -d ~/.dfrab/backups/$2 ]] ; then
     echo "$2 already exists, use a different name."
     exit 21
+  fi
+  if [[ "$2" == '.' ]] ; then
+    echo "Fatal: cannot create backup ."
+    exit 1
+  fi
+  if [[ "$2" == '..' ]] ; then
+    echo "Fatal: cannot create backup .."
+    exit 1
   fi
   if [[ ! -d ~/.dfrab/backups/$2 ]] ; then
     cp -r $CURRENT_DFRAB_PROFILE ~/.dfrab/backups/$2
@@ -87,6 +110,14 @@ fi
 if [[ "$1" == 'unlink' ]] ; then
   if [[ ! -e ~/.dfrab/current/$2 ]] ; then
     echo "Can't unlink non existing file"
+    exit 1
+  fi
+  if [[ "$2" == '.' ]] ; then
+    echo "Fatal: cannot modify ."
+    exit 1
+  fi
+  if [[ "$2" == '..' ]] ; then
+    echo "Fatal: cannot modify .."
     exit 1
   fi
   if [[ ! -e "$2" ]] ; then
